apiVersion: v1
kind: Service
metadata:
  name: sentio-engine-service
spec:
  # Этот тип сервиса (ClusterIP) делает его доступным только внутри кластера.
  # Для доступа извне потребуется Ingress Controller или сервис типа NodePort/LoadBalancer.
  type: ClusterIP
  selector:
    app: sentio-engine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
