# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentio_engine/schemas/sentio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sentio_engine/schemas/sentio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"sentio_engine/schemas/sentio.proto\x12\x06sentio\"m\n\x08Stimulus\x12\x30\n\x08\x65motions\x18\x01 \x03(\x0b\x32\x1e.sentio.Stimulus.EmotionsEntry\x1a/\n\rEmotionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\x9e\x01\n\x0e\x45motionalState\x12\x36\n\x08\x65motions\x18\x01 \x03(\x0b\x32$.sentio.EmotionalState.EmotionsEntry\x12\x14\n\x0cprimary_mood\x18\x02 \x01(\t\x12\r\n\x05\x63\x61use\x18\x03 \x01(\t\x1a/\n\rEmotionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"Q\n\x06Report\x12/\n\x0f\x65motional_state\x18\x01 \x01(\x0b\x32\x16.sentio.EmotionalState\x12\x16\n\x0e\x63omplex_states\x18\x02 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentio_engine.schemas.sentio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STIMULUS_EMOTIONSENTRY']._loaded_options = None
  _globals['_STIMULUS_EMOTIONSENTRY']._serialized_options = b'8\001'
  _globals['_EMOTIONALSTATE_EMOTIONSENTRY']._loaded_options = None
  _globals['_EMOTIONALSTATE_EMOTIONSENTRY']._serialized_options = b'8\001'
  _globals['_STIMULUS']._serialized_start=46
  _globals['_STIMULUS']._serialized_end=155
  _globals['_STIMULUS_EMOTIONSENTRY']._serialized_start=108
  _globals['_STIMULUS_EMOTIONSENTRY']._serialized_end=155
  _globals['_EMOTIONALSTATE']._serialized_start=158
  _globals['_EMOTIONALSTATE']._serialized_end=316
  _globals['_EMOTIONALSTATE_EMOTIONSENTRY']._serialized_start=108
  _globals['_EMOTIONALSTATE_EMOTIONSENTRY']._serialized_end=155
  _globals['_REPORT']._serialized_start=318
  _globals['_REPORT']._serialized_end=399
# @@protoc_insertion_point(module_scope)
